spring:
  cloud:
    config:
      allow-override: true
      override-none: true

management.security.enabled: false
management.endpoints.web.exposure.include: "*"
spring.cloud.refresh.refreshable: false
logging.level.org.springframework: INFO

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
---
spring:
  profiles: mysql
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    url: jdbc:mysql://localhost:3306/employees?useSSL=false
    username: root
    password: root
    initialization-mode: ALWAYS